// What the settings panel shows: sections of controls, each on a tab. adv = only with Advanced settings,
// when = only when it applies to the current design, custom = a section drawn by its own module.
import { LAYOUT_NAMES } from '../core/layouts.js';
import { PIECES } from '../core/pieces.js';

const FONTS = ['Maze Block', 'Impact', 'Arial Black', 'Verdana', 'Georgia', 'Trebuchet MS', 'Courier New', 'DejaVu Sans', 'Liberation Sans', 'monospace', 'serif'];
export const SCHEMA = [
  { id: 'structure', title: 'Structure', ico: 'cube', tab: 'shape', items: [
    { k: 'piece', type: 'select', label: 'Piece', options: PIECES, help: 'Single wall pieces, junctions, or a whole generated maze.' },
    { k: 'cornerPreview', type: 'toggle', label: 'Show attached walls', when: P => P.piece === 'corner', help: 'Preview the corner with a straight wall on each arm (only the corner is exported).' },
    { k: 'layout', type: 'select', label: 'Layout', options: LAYOUT_NAMES, help: 'The overall massing of the wall.' },
    { k: 'seed', type: 'seed', label: 'Seed', help: 'Same seed + same settings = same wall, every time.' },
    { k: 'width', type: 'range', label: 'Width / arm length', min: 8, max: 96, step: 1, unit: 'blocks', when: P => P.piece !== 'maze', help: 'For corners and junctions: overall size, measured on the outside.' },
    { k: 'thickness', type: 'range', label: 'Thickness', min: 6, max: 48, step: 1, unit: 'blocks', when: P => P.piece !== 'maze' },
    { k: 'seamMatch', type: 'toggle', label: 'Seam matching', when: P => P.piece === 'straight', help: 'Both ends of every wall get the same joint profile and height, so walls with different seeds line up where they meet. Try Tile × to see.' },
    { adv: true, k: 'seamPattern', type: 'range', label: 'Seam pattern', min: 0, max: 50, step: 1, when: P => P.piece === 'straight' && P.seamMatch, help: 'Use the same pattern number for every wall in one run.' },
  ]},
  { id: 'skyline', title: 'Height & skyline', ico: 'skyline', tab: 'shape', items: [
    { k: 'heightMin', type: 'range', label: 'Min height', min: 16, max: 200, step: 1, unit: 'blocks' },
    { k: 'heightMax', type: 'range', label: 'Max height', min: 16, max: 200, step: 1, unit: 'blocks', help: 'The skyline varies between min and max.' },
    { k: 'skylineRough', type: 'range', label: 'Skyline roughness', min: 0, max: 1, step: 0.01, help: 'Each top slab drops by its own amount, so the top steps up and down instead of running level.' },
    { k: 'skylineSlope', type: 'range', label: 'Skyline slope', min: -1, max: 1, step: 0.01, help: 'Leans the whole skyline down to the left (−) or right (+), in steps that follow the slabs.' },
    { k: 'ruin', type: 'range', label: 'Broken tops', min: 0, max: 1, step: 0.01, help: 'Knocks ragged chunks out of the wall top, mostly at its edges. Rain and ivy follow the broken shape.' },
  ]},
  { id: 'maze', title: 'Maze', ico: 'maze', tab: 'shape', when: P => P.piece === 'maze', items: [
    { k: 'mazeCols', type: 'range', label: 'Cells across', min: 2, max: 16, step: 1, when: P => P.piece === 'maze' },
    { k: 'mazeRows', type: 'range', label: 'Cells deep', min: 2, max: 16, step: 1, when: P => P.piece === 'maze' },
    { k: 'mazeCorridor', type: 'range', label: 'Corridor width', min: 3, max: 30, step: 1, unit: 'blocks', when: P => P.piece === 'maze' },
    { k: 'mazeWall', type: 'range', label: 'Wall thickness', min: 4, max: 30, step: 1, unit: 'blocks', when: P => P.piece === 'maze' },
    { k: 'mazeBraid', type: 'range', label: 'Loops', min: 0, max: 1, step: 0.01, when: P => P.piece === 'maze', help: 'Share of dead ends opened up into loops (0 = a perfect maze with one route).' },
    { k: 'glade', type: 'toggle', label: 'Glade', when: P => P.piece === 'maze', help: 'An open square in the middle with a gate in each side.' },
    { k: 'gladeSize', type: 'range', label: 'Glade size', min: 1, max: 6, step: 1, unit: 'cells', when: P => P.piece === 'maze' && P.glade },
  ]},
  { id: 'faces', title: 'Faces', ico: 'faces', tab: 'shape', when: P => P.piece !== 'maze', custom: 'faces' },
  { id: 'layoutx', title: 'Layout options', ico: 'sliders', tab: 'shape', items: [
    { k: 'towerCount', type: 'range', label: 'Towers', min: 1, max: 6, step: 1, when: P => P.layout === 'towers' || P.backLayout === 'towers' },
    { k: 'towerGap', type: 'range', label: 'Gap width', min: 1, max: 12, step: 1, when: P => P.layout === 'towers' || P.backLayout === 'towers' },
    { k: 'towerGapDepth', type: 'range', label: 'Gap depth', min: 2, max: 20, step: 1, when: P => P.layout === 'towers' || P.backLayout === 'towers' },
    { k: 'cubeWidth', type: 'range', label: 'Cube width', min: 6, max: 60, step: 1, when: P => P.layout === 'cantilever' || P.backLayout === 'cantilever' },
    { k: 'cubeHeight', type: 'range', label: 'Cube height', min: 6, max: 40, step: 1, when: P => P.layout === 'cantilever' || P.backLayout === 'cantilever' },
    { k: 'overhang', type: 'range', label: 'Overhang', min: 1, max: 10, step: 1, when: P => P.layout === 'cantilever' || P.backLayout === 'cantilever' },
    { k: 'passageHeight', type: 'range', label: 'Passage height', min: 4, max: 40, step: 1, when: P => P.layout === 'beam' || P.backLayout === 'beam' },
    { k: 'passageDepth', type: 'range', label: 'Passage depth', min: 3, max: 30, step: 1, when: P => P.layout === 'beam' || P.backLayout === 'beam' },
    { k: 'beamHeight', type: 'range', label: 'Beam height', min: 2, max: 16, step: 1, when: P => P.layout === 'beam' || P.backLayout === 'beam' },
    { k: 'slabWidth', type: 'range', label: 'Slab width', min: 6, max: 90, step: 1, when: P => P.layout === 'slab' || P.backLayout === 'slab' },
    { k: 'slabHeight', type: 'range', label: 'Slab height', min: 10, max: 150, step: 1, when: P => P.layout === 'slab' || P.backLayout === 'slab' },
    { k: '_none', type: 'note', label: 'Stacked tiers has no extra options — see Slabs & relief.', when: P => P.layout === 'stacked' && !['towers', 'cantilever', 'beam', 'slab'].includes(P.backLayout) },
  ]},
  { id: 'back', title: 'Back & ends', ico: 'back', tab: 'shape', items: [
    { k: 'doubleSided', type: 'toggle', label: 'Detailed back', help: 'Give the back its own design (otherwise flat but weathered).' },
    { k: 'backLayout', type: 'select', label: 'Back layout', options: { auto: 'Random', same: 'Same as front', ...LAYOUT_NAMES }, when: P => P.doubleSided },
    { adv: true, k: 'backSeedOffset', type: 'range', label: 'Back variation', min: 1, max: 9999, step: 1, when: P => P.doubleSided, help: 'Changes the back without touching the front.' },
    { adv: true, k: 'backFeatures', type: 'select', label: 'Back features', options: { same: 'Same as front', fewer: 'Fewer', none: 'None' }, when: P => P.doubleSided },
    { adv: true, k: 'minCore', type: 'range', label: 'Min core', min: 2, max: 12, step: 1, unit: 'blocks', help: 'Solid thickness kept between front and back relief.' },
    { adv: true, k: 'endDetail', type: 'toggle', label: 'End-face detail', help: 'Give the two ends their own slab design (joints line up with the front). Off = flat but weathered.' },
    { adv: true, k: 'endRelief', type: 'range', label: 'End relief', min: 0, max: 5, step: 1, unit: 'blocks', when: P => P.endDetail, help: 'How far the end-face slabs step in and out.' },
  ]},
  { id: 'base', title: 'Base', ico: 'base', tab: 'shape', items: [
    { k: 'fins', type: 'toggle', label: 'Buttress fins' },
    { adv: true, k: 'finHeightMin', type: 'range', label: 'Fin zone min', min: 4, max: 60, step: 1, when: P => P.fins },
    { adv: true, k: 'finHeightMax', type: 'range', label: 'Fin zone max', min: 4, max: 60, step: 1, when: P => P.fins },
    { adv: true, k: 'finWidth', type: 'range', label: 'Fin width', min: 1, max: 6, step: 1, when: P => P.fins },
    { adv: true, k: 'finGapMin', type: 'range', label: 'Fin gap min', min: 1, max: 12, step: 1, when: P => P.fins },
    { adv: true, k: 'finGapMax', type: 'range', label: 'Fin gap max', min: 1, max: 12, step: 1, when: P => P.fins },
    { adv: true, k: 'plinthHeight', type: 'range', label: 'Plinth height', min: 0, max: 6, step: 1 },
    { adv: true, k: 'plinthDepth', type: 'range', label: 'Plinth depth', min: 0, max: 6, step: 1, when: P => P.plinthHeight > 0 },
  ]},
  { id: 'massing', title: 'Slabs & relief', ico: 'slabs', tab: 'detail', items: [
    { k: 'reliefMax', type: 'range', label: 'Relief depth', min: 0, max: 10, step: 1, unit: 'blocks', help: 'How far slabs step in and out.' },
    { k: 'panelContrast', type: 'range', label: 'Panel distinction', min: 0, max: 1, step: 0.01, help: 'Makes every slab stand out: its own shade and block, calmer texture inside, deeper and darker joints between slabs.' },
    { k: 'panelDetail', type: 'range', label: 'Panel detail', min: 0, max: 1, step: 0.01, help: 'Share of big slabs given inset panels, pilaster strips or a formwork grid.' },
    { adv: true, k: 'tierMin', type: 'range', label: 'Tier height min', min: 3, max: 40, step: 1 },
    { adv: true, k: 'tierMax', type: 'range', label: 'Tier height max', min: 3, max: 40, step: 1 },
    { adv: true, k: 'splitChance', type: 'range', label: 'Slab splitting', min: 0, max: 1, step: 0.01, help: 'Chance a tier is split into 2–3 slabs.' },
    { adv: true, k: 'minSlab', type: 'range', label: 'Min slab width', min: 3, max: 24, step: 1 },
    { adv: true, k: 'slabTarget', type: 'range', label: 'Typical slab width', min: 5, max: 40, step: 1, unit: 'blocks', help: 'Wide walls split into more slabs so they never become big flat panels.' },
    { adv: true, k: 'bayWidth', type: 'range', label: 'Bay width', min: 8, max: 60, step: 1, unit: 'blocks', help: 'Wide walls are built as independent bays, each with its own depth, joints and skyline.' },
    { adv: true, k: 'bayRelief', type: 'range', label: 'Bay relief', min: 0, max: 8, step: 1, unit: 'blocks', help: 'How far whole bays step forward or back from each other.' },
    { adv: true, k: 'ledgeChance', type: 'range', label: 'Ledge caps', min: 0, max: 1, step: 0.01, help: 'Projecting band on top of slabs.' },
    { adv: true, k: 'jointDepth', type: 'range', label: 'Joint depth', min: 0, max: 3, step: 1 },
    { adv: true, k: 'grooveDepth', type: 'range', label: 'Groove depth', min: 0, max: 6, step: 1 },
    { adv: true, k: 'formlineChance', type: 'range', label: 'Formwork lines', min: 0, max: 1, step: 0.01 },
  ]},
  { id: 'features', title: 'Features', ico: 'target', tab: 'detail', items: [
    { k: 'portholes', type: 'range', label: 'Port-holes', min: 0, max: 8, step: 1 },
    { adv: true, k: 'portholeRadius', type: 'range', label: 'Port-hole radius', min: 1, max: 5, step: 1, when: P => P.portholes > 0 },
    { k: 'grilles', type: 'range', label: 'Vent grilles', min: 0, max: 12, step: 1 },
    { adv: true, k: 'grilleMin', type: 'range', label: 'Grille size min', min: 3, max: 12, step: 1, when: P => P.grilles > 0 },
    { adv: true, k: 'grilleMax', type: 'range', label: 'Grille size max', min: 3, max: 12, step: 1, when: P => P.grilles > 0 },
    { k: 'hazards', type: 'range', label: 'Hazard panels', min: 0, max: 6, step: 1 },
    { adv: true, k: 'hazardStripe', type: 'range', label: 'Stripe width', min: 1, max: 4, step: 1, when: P => P.hazards > 0 },
    { adv: true, k: 'hazardWear', type: 'range', label: 'Stripe wear', min: 0, max: 0.6, step: 0.01, when: P => P.hazards > 0 },
    { k: 'channels', type: 'range', label: 'Service channels', min: 0, max: 8, step: 1 },
    { adv: true, k: 'channelPairs', type: 'toggle', label: 'Twin channels', when: P => P.channels > 0 },
    { k: 'doorways', type: 'range', label: 'Doorways', min: 0, max: 6, step: 1 },
    { adv: true, k: 'doorWidth', type: 'range', label: 'Door width', min: 1, max: 12, step: 1, when: P => P.doorways > 0 },
    { adv: true, k: 'doorHeight', type: 'range', label: 'Door height', min: 2, max: 20, step: 1, when: P => P.doorways > 0 },
    { adv: true, k: 'doorDepth', type: 'range', label: 'Door depth', min: 2, max: 20, step: 1, when: P => P.doorways > 0 },
    { k: 'windows', type: 'range', label: 'Small windows', min: 0, max: 12, step: 1 },
    { adv: true, k: 'tieChance', type: 'range', label: 'Tie-hole slabs', min: 0, max: 1, step: 0.01, help: 'Share of slabs with formwork tie-holes.' },
    { adv: true, k: 'tieSpacing', type: 'range', label: 'Tie-hole spacing', min: 3, max: 10, step: 1 },
  ]},
  { id: 'lettering', title: 'Sector lettering', ico: 'type', tab: 'detail', items: [
    { k: 'numberText', type: 'text', label: 'Text', help: 'Numbers or letters, e.g. 5, 7, A2. Leave empty for none.' },
    { k: 'numberFont', type: 'select', label: 'Font', options: Object.fromEntries(FONTS.map(f => [f, f])), help: 'Maze Block is the film-style stencil (digits).' },
    { k: 'numberHeight', type: 'range', label: 'Height', min: 5, max: 90, step: 1, unit: 'blocks' },
    { k: 'numberPosX', type: 'range', label: 'Position X', min: 0, max: 1, step: 0.01 },
    { k: 'numberPosY', type: 'range', label: 'Position Y', min: 0, max: 1, step: 0.01 },
    { k: 'numberStyle', type: 'select', label: 'Style', options: { painted: 'Painted', raised: 'Raised', inset: 'Inset' } },
    { k: 'numberSide', type: 'select', label: 'Side', options: { front: 'Front', back: 'Back', both: 'Both' } },
    { adv: true, k: 'numberWidth', type: 'range', label: 'Width', min: 0.4, max: 2.5, step: 0.05, unit: '×' },
    { adv: true, k: 'numberWear', type: 'range', label: 'Paint wear', min: 0, max: 0.8, step: 0.01 },
    { adv: true, k: 'paintVariation', type: 'range', label: 'Paint variation', min: 0, max: 1, step: 0.01, help: 'Mix of the secondary paint block.' },
  ]},
  { id: 'rain', title: 'Rain & dirt', ico: 'rain', tab: 'weather', items: [
    { k: 'streakStrength', type: 'range', label: 'Rain dirt', min: 0, max: 2.5, step: 0.01, help: 'How much dirt rainwater leaves where it runs off tops and down faces.' },
    { k: 'windDir', type: 'range', label: 'Wind from', min: 0, max: 359, step: 1, unit: 'degrees', help: '0 = north, 90 = east, 180 = south (the side the fronts face), 270 = west.' },
    { k: 'windRain', type: 'range', label: 'Wind-driven rain', min: 0, max: 1.5, step: 0.01, help: 'Rain blown onto the faces that look into the wind; sheltered faces stay dry.' },
    { k: 'sunDrying', type: 'range', label: 'Sun drying', min: 0, max: 1, step: 0.01, help: 'South faces dry out and stay cleaner; north faces stay damp and greener.' },
    { adv: true, k: 'streakLength', type: 'range', label: 'Streak length', min: 4, max: 90, step: 1, help: 'How far water runs down a face before it soaks in.' },
    { adv: true, k: 'streakCoverage', type: 'range', label: 'Drip spread', min: 0, max: 1, step: 0.01, help: '0 = water gathers into a few heavy drips; 1 = it spills evenly along every edge.' },
    { adv: true, k: 'soffitCreep', type: 'range', label: 'Soffit creep', min: 0, max: 1, step: 0.01, help: 'Water clinging to ledge undersides and running back to stain the wall just below.' },
    { adv: true, k: 'washing', type: 'range', label: 'Washing', min: 0, max: 1, step: 0.01, help: 'Heavy flows wash the middle of a streak clean, leaving darker edges and tails.' },
  ]},
  { id: 'weather', title: 'Surface & wear', ico: 'drop', tab: 'weather', items: [
    { k: 'baseTone', type: 'range', label: 'Base tone', min: -0.2, max: 0.8, step: 0.01, help: 'Lower = lighter, sun-bleached concrete.' },
    { k: 'moss', type: 'range', label: 'Moss', min: 0, max: 3, step: 0.05 },
    { k: 'cracks', type: 'range', label: 'Cracks', min: 0, max: 20, step: 1 },
    { k: 'rust', type: 'range', label: 'Rust amount', min: 0, max: 2, step: 0.01 },
    { adv: true, k: 'grimeHeight', type: 'range', label: 'Ground grime height', min: 0, max: 40, step: 1 },
    { adv: true, k: 'grimeStrength', type: 'range', label: 'Ground grime', min: 0, max: 1, step: 0.01 },
    { adv: true, k: 'panelTone', type: 'range', label: 'Slab tone variation', min: 0, max: 0.25, step: 0.005 },
    { adv: true, k: 'largeNoise', type: 'range', label: 'Large blotches', min: 0, max: 0.5, step: 0.01 },
    { adv: true, k: 'fineNoise', type: 'range', label: 'Fine mottling', min: 0, max: 0.4, step: 0.01 },
    { adv: true, k: 'speckle', type: 'range', label: 'Speckle', min: 0, max: 0.3, step: 0.01 },
    { adv: true, k: 'patchSize', type: 'range', label: 'Material patch size', min: 0.6, max: 8, step: 0.1 },
    { adv: true, k: 'crackRust', type: 'range', label: 'Rusty cracks', min: 0, max: 1, step: 0.01 },
    { adv: true, k: 'chips', type: 'range', label: 'Chipped corners', min: 0, max: 1, step: 0.01 },
    { adv: true, k: 'pockmarks', type: 'range', label: 'Pockmarks', min: 0, max: 0.06, step: 0.001 },
  ]},
  { id: 'ivy', title: 'Ivy & vines', ico: 'leaf', tab: 'weather', items: [
    { k: 'ivy', type: 'toggle', label: 'Grow ivy', help: 'Vines, leaf clumps and moss grown onto the finished structure.' },
    { k: 'ivyOvergrowth', type: 'range', label: 'Overgrowth', min: 0, max: 1, step: 0.01, when: P => P.ivy, help: 'Master control: more strands, longer reach. 1 = heavily overgrown.' },
    { k: 'ivyAmount', type: 'range', label: 'Hanging growth', min: 0, max: 1, step: 0.01, when: P => P.ivy, help: 'How often ivy takes root on ledges and the wall top and grows down.' },
    { k: 'ivyClimb', type: 'range', label: 'Climbing from ground', min: 0, max: 1, step: 0.01, when: P => P.ivy },
    { k: 'ivyLeaves', type: 'range', label: 'Leaf clumps', min: 0, max: 1, step: 0.01, when: P => P.ivy, help: 'Bushy leaves spilling over ledges above the vines.' },
    { k: 'ivyLeafBlock', type: 'select', label: 'Leaf block', when: P => P.ivy, options: { azalea_leaves: 'Azalea (+ flowering)', oak_leaves: 'Oak', dark_oak_leaves: 'Dark oak', jungle_leaves: 'Jungle', spruce_leaves: 'Spruce', mangrove_leaves: 'Mangrove', birch_leaves: 'Birch' } },
    { adv: true, k: 'ivyLength', type: 'range', label: 'Hanging reach', min: 2, max: 70, step: 1, unit: 'blocks', when: P => P.ivy, help: 'How far hanging strands can grow (they reach further in shade).' },
    { adv: true, k: 'ivyWidth', type: 'range', label: 'Clump width', min: 0, max: 12, step: 1, when: P => P.ivy, help: 'Strands per root clump.' },
    { adv: true, k: 'ivyClimbHeight', type: 'range', label: 'Climb height', min: 2, max: 70, step: 1, unit: 'blocks', when: P => P.ivy },
    { adv: true, k: 'ivyMoss', type: 'range', label: 'Moss on ledges', min: 0, max: 1, step: 0.01, when: P => P.ivy },
    { adv: true, k: 'ivyBranching', type: 'range', label: 'Branching', min: 0, max: 0.25, step: 0.005, when: P => P.ivy, help: 'How often a strand sends out a thinner side shoot.' },
    { adv: true, k: 'ivyWander', type: 'range', label: 'Wander', min: 0, max: 1.5, step: 0.01, when: P => P.ivy, help: 'How much strands drift sideways instead of running straight up or down.' },
    { adv: true, k: 'ivyShade', type: 'range', label: 'Shade & damp preference', min: 0, max: 1.5, step: 0.01, when: P => P.ivy, help: 'Higher = ivy crowds into shaded, damp spots (north faces, grooves, under ledges, stained areas) and avoids dry sun.' },
    { adv: true, k: 'ivyDryShade', type: 'range', label: 'Dry-shade growth', min: 0, max: 1, step: 0.01, when: P => P.ivy, help: 'Lets ivy take hold on dry but shaded walls too, not only where rain keeps them damp.' },
    { adv: true, k: 'ivyCluster', type: 'range', label: 'Clustering', min: 2, max: 24, step: 1, when: P => P.ivy, help: 'Bigger = ivy gathers in fewer, larger overgrown areas.' },
    { adv: true, k: 'ivyVariation', type: 'range', label: 'Ivy variation', min: 1, max: 999, step: 1, when: P => P.ivy, help: 'Re-rolls the ivy without changing the wall.' },
  ]},
  { id: 'palette', title: 'Block palette', ico: 'palette', tab: 'blocks', custom: 'palette' },
];
export const ROLES = [
  ['grime', 'Grime / moss'], ['crack', 'Cracks'], ['deep', 'Deep shadow'], ['rust', 'Rust'], ['rust2', 'Rust fade'],
  ['paint', 'Paint'], ['paint2', 'Paint (secondary)'], ['porthole', 'Port-hole metal'], ['grilleFrame', 'Grille frame'],
  ['hazardA', 'Hazard stripe A'], ['hazardB', 'Hazard stripe B'], ['interior', 'Hidden interior'],
];
export const BAND_TONES = ['#d6d6d6', '#c3c3c3', '#afafaf', '#9d9d9d', '#8a8a8a', '#777', '#636363', '#4d4d4d', '#393939'];
