// Default settings, the default palette and the built-in presets.
export const DEFAULT_PALETTE = {
  bands: [
    ['smooth_stone'], ['smooth_stone', 'andesite'], ['andesite', 'polished_andesite'], ['polished_andesite', 'stone'],
    ['stone', 'stone_bricks'], ['stone_bricks', 'cracked_stone_bricks', 'cobblestone'], ['cracked_stone_bricks', 'cobblestone'],
    ['cobblestone', 'gray_concrete'], ['gray_concrete'],
  ],
  grime: 'mossy_stone_bricks', crack: 'cracked_stone_bricks', deep: 'gray_concrete', rust: 'brown_terracotta', rust2: 'cobblestone',
  paint: 'red_terracotta', paint2: 'brown_terracotta', porthole: 'brown_terracotta', grilleFrame: 'gray_concrete',
  hazardA: 'yellow_terracotta', hazardB: 'gray_concrete', bars: 'iron_bars', interior: 'stone',
};
export const DEFAULTS = {
  name: 'my_wall', layout: 'stacked', seed: 1234, width: 20, heightMin: 70, heightMax: 74, thickness: 24,
  doubleSided: true, backLayout: 'auto', backSeedOffset: 9000, backFeatures: 'same', minCore: 4, endDetail: true, endRelief: 2,
  reliefMax: 4, tierMin: 8, tierMax: 14, splitChance: 0.6, minSlab: 5, slabTarget: 11, panelDetail: 0.55, skylineRough: 0.35, skylineSlope: 0, ruin: 0, seamMatch: false, seamPattern: 0, faceOverrides: {}, bayWidth: 20, bayRelief: 3, ledgeChance: 0.5, jointDepth: 1, grooveDepth: 2, formlineChance: 0.5,
  fins: true, finHeightMin: 15, finHeightMax: 22, finWidth: 2, finGapMin: 3, finGapMax: 5, plinthHeight: 2, plinthDepth: 2,
  towerCount: 2, towerGap: 2, towerGapDepth: 8, cubeWidth: 12, cubeHeight: 14, overhang: 5,
  passageHeight: 14, passageDepth: 14, beamHeight: 6, slabWidth: 16, slabHeight: 43,
  numberText: '', numberFont: 'Maze Block', numberHeight: 21, numberWidth: 1.0, numberPosX: 0.5, numberPosY: 0.5,
  numberWear: 0.16, numberStyle: 'painted', numberSide: 'front', paintVariation: 0.18,
  portholes: 0, portholeRadius: 2, grilles: 0, grilleMin: 3, grilleMax: 5, hazards: 0, hazardStripe: 2, hazardWear: 0.12,
  channels: 0, channelPairs: true, doorways: 0, doorWidth: 3, doorHeight: 5, doorDepth: 8, windows: 0,
  tieChance: 0.4, tieSpacing: 5,
  baseTone: 0.20, panelTone: 0.05, panelContrast: 0, largeNoise: 0.16, fineNoise: 0.07, speckle: 0.05, patchSize: 2.2,
  streakStrength: 1.05, streakLength: 32, streakCoverage: 0.35, windDir: 225, windRain: 0.35, soffitCreep: 0.6, sunDrying: 0.5, washing: 0.35, grimeHeight: 10, grimeStrength: 0.30, moss: 1.0,
  cracks: 2, crackRust: 0.4, rust: 1.0, chips: 0.5, pockmarks: 0.003,
  palette: DEFAULT_PALETTE,
  piece: 'straight', cornerPreview: true, mazeCols: 5, mazeRows: 5, mazeCorridor: 9, mazeWall: 8, mazeBraid: 0.15, glade: true, gladeSize: 1,
  ivy: true, ivyAmount: 0.35, ivyLength: 22, ivyWidth: 4, ivyClimb: 0.35, ivyClimbHeight: 14, ivyLeaves: 0.55, ivyMoss: 0.35, ivyCluster: 7, ivyVariation: 1, ivyLeafBlock: 'oak_leaves', ivyBranching: 0.07, ivyWander: 0.45, ivyShade: 0.7, ivyOvergrowth: 0.25, ivyDryShade: 0.35,
  autoPalette: true, autoRoles: true, autoContrast: 1.0, autoSpread: 0.08, autoSatMax: 0.12, roleLock: {},
  autoBlocks: ['smooth_stone', 'andesite', 'polished_andesite', 'stone', 'stone_bricks', 'cracked_stone_bricks', 'cobblestone',
    'mossy_stone_bricks', 'gray_concrete', 'brown_terracotta', 'red_terracotta', 'yellow_terracotta'],
};
export const PRESETS = {
  'Classic wall': { layout: 'stacked', fins: true },
  'Classic sector 7': { layout: 'stacked', fins: true, numberText: '7', numberHeight: 21, numberWidth: 1.0, numberPosY: 0.45 },
  'Twin towers': { layout: 'towers', fins: false, channels: 1, grilles: 1 },
  'Cantilever block': { layout: 'cantilever', fins: false, portholes: 1, hazards: 1, reliefMax: 4 },
  'Vent wall': { layout: 'stacked', fins: false, grilles: 3, windows: 2, doorways: 1, channels: 1, reliefMax: 4, tierMin: 9, tierMax: 15 },
  'Beam passage (40 wide)': { layout: 'beam', width: 40, fins: false, portholes: 1, channels: 1 },
  'Sector slab 5': { layout: 'slab', fins: false, numberText: '5', numberHeight: 28, numberWidth: 1.0, doorways: 1 },
  'Glade door wall (60 wide)': { layout: 'towers', width: 60, towerCount: 3, towerGap: 6, towerGapDepth: 14, fins: true, channels: 2, heightMin: 72, heightMax: 76 },
  'Corner piece': { piece: 'corner', layout: 'stacked', width: 30, fins: true },
  'Overgrown corner': { piece: 'corner', layout: 'stacked', width: 30, fins: true, ivyAmount: 1, ivyClimb: 0.95, ivyLeaves: 0.9, ivyMoss: 0.7, ivyLength: 46, ivyClimbHeight: 30, ivyWidth: 7, ivyBranching: 0.1, moss: 1.8 },
  'Overgrown wall': { layout: 'stacked', fins: true, ivyAmount: 1, ivyClimb: 0.95, ivyLeaves: 0.9, ivyMoss: 0.7, ivyLength: 46, ivyClimbHeight: 30, ivyWidth: 7, ivyBranching: 0.1, moss: 1.8, streakStrength: 1.3 },
  'T-junction': { piece: 'tee', layout: 'stacked', width: 44, fins: true },
  'Crossroads': { piece: 'cross', layout: 'stacked', width: 56, fins: true },
  'Maze with Glade': { piece: 'maze', layout: 'stacked', mazeCols: 5, mazeRows: 5, mazeCorridor: 9, mazeWall: 8, glade: true, fins: false, ivyAmount: 0.45 },
  'Big maze (9×9)': { piece: 'maze', layout: 'stacked', mazeCols: 9, mazeRows: 9, mazeCorridor: 8, mazeWall: 6, glade: true, gladeSize: 3, fins: false, heightMin: 40, heightMax: 48, ivyAmount: 0.4 },
  'Ruined low wall': { layout: 'stacked', heightMin: 30, heightMax: 42, ruin: 0.6, skylineRough: 0.6, cracks: 7, chips: 0.9, pockmarks: 0.02, moss: 2, streakStrength: 1.4, fins: false },
};
