// Bundles the parts of three.js the app uses into web/lib/three.js (tree-shaken, minified).
// Run after updating the `three` dev dependency:  npm run vendor
import { build } from 'esbuild';

const entry = `
export {
  WebGLRenderer, Scene, PerspectiveCamera, Group, Mesh, BufferGeometry, InterleavedBuffer, InterleavedBufferAttribute,
  PlaneGeometry, BoxGeometry, ConeGeometry, GridHelper, HemisphereLight, DirectionalLight, Fog,
  MeshLambertMaterial, MeshBasicMaterial, MeshDepthMaterial, CanvasTexture, DataArrayTexture,
  Box3, Sphere, Vector3, Color, MathUtils, SRGBColorSpace, ACESFilmicToneMapping, PCFShadowMap, NearestFilter,
  NearestMipmapLinearFilter, RepeatWrapping, DoubleSide,
} from 'three';
export { OrbitControls } from 'three/addons/controls/OrbitControls.js';
`;
await build({
  stdin: { contents: entry, resolveDir: process.cwd(), loader: 'js' },
  bundle: true, format: 'esm', minify: true, target: 'es2022', outfile: 'web/lib/three.js',
  banner: { js: '// three.js (MIT) — generated by tools/vendor.mjs, do not edit' }, legalComments: 'none',
});
